spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    open-in-view: false

  sql:
    init:
      mode: always

jwt:
  secret:
    key: ${SECRET_KEY}
  access:
    time: 1800000    # 30분 1800000
  refresh:
    time: 1209600000     # 14일